version: '3.8'

services:
  database:
    image: postgres
    container_name: portfolio-database
    restart: always
    ports:
      - "54032:5432"
    env_file:
      - .env.local

  adminer:
    image: adminer
    container_name: portfolio-adminer
    restart: always
    ports:
      - "54080:8080"