version: '3.8'

services:
  app:
    container_name: portfolio-app
    build:
      context: .
      target: production
    restart: unless-stopped
    env_file: .env.local
    volumes:
      - .:/app
    ports:
      - "55111:3000"
    working_dir: /app

  database:
    image: postgres
    container_name: portfolio-database
    restart: unless-stopped
    ports:
      - "55032:5432"
    env_file:
      - .env.local

  adminer:
    image: adminer
    container_name: portfolio-adminer
    restart: unless-stopped
    ports:
      - "55080:8080"
