version: '3.8'

services:
  app:
    container_name: portfolio-app
    build:
      context: .
      target: production
    restart: unless-stopped
    env_file: .env.local
    volumes:
      - .:/app
    ports:
      - "55111:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`timeuh.fr`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
    networks:
      - traefik_web
    working_dir: /app

  database:
    image: postgres
    container_name: portfolio-database
    restart: unless-stopped
    ports:
      - "55032:5432"
    networks:
      - traefik_web
    env_file:
      - .env.local

  adminer:
    image: adminer
    container_name: portfolio-adminer
    restart: unless-stopped
    ports:
      - "55080:8080"
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin-portfolio.rule=Host(`admin.portfolio.timeuh.fr`)"
      - "traefik.http.routers.admin-portfolio.entrypoints=websecure"
      - "traefik.http.routers.admin-portfolio.tls.certresolver=myresolver"

networks:
  traefik_web:
    external: true
  default:
    driver: bridge
